#!/bin/bash
set -e
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE DATABASE shadow;
  CREATE ROLE ${POSTGRAPHILE_DB_USER} WITH LOGIN PASSWORD '${POSTGRAPHILE_DB_PASS}' NOINHERIT;

  CREATE ROLE ${POSTGRAPHILE_ROLE_ANONYMOUS};
  GRANT ANON TO ${POSTGRAPHILE_DB_USER};

  CREATE ROLE ${POSTGRAPHILE_ROLE_USER};
  GRANT PERSON TO ${POSTGRAPHILE_DB_USER};
EOSQL
