#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE DATABASE shadow;
  CREATE ROLE ${POSTGRAPHILE_DB_USER} WITH LOGIN PASSWORD '${POSTGRAPHILE_DB_PASS}' NOINHERIT;

  CREATE ROLE ${POSTGRAPHILE_ANON_ROLE};
  GRANT ${POSTGRAPHILE_ANON_ROLE} TO ${POSTGRAPHILE_DB_USER};

  CREATE ROLE "${POSTGRAPHILE_USER_ROLE}";
  GRANT "${POSTGRAPHILE_USER_ROLE}" TO ${POSTGRAPHILE_DB_USER};
EOSQL
