services:
  postgres:
    image: postgres:16-alpine
    restart: always
    env_file: .env
    volumes:
      - ./.docker/volumes/database/data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_PORT}:5432"
