services:
  postgres:
    image: postgres:16-alpine
    restart: always
    volumes:
      - ./.docker/volumes/database/data:/var/lib/postgresql/data
    ports:
      - "${PGPORT}:5432"
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
